### ISSUE TITLE
Support import and refresh operations

### ISSUE THREAD

**Issue by cooperaj** [ryanwholey/terraform-provider-pihole#23]
In order to get this to work (which it otherwise does spectacularly) I had to remove all pre-existing configured CNAME and DNS entries. I had attempted to update using `-refresh-only` and no import information is listed in the docs. I'm not even sure what would be required to get that working.

https://learn.hashicorp.com/tutorials/terraform/refresh

**Comment by ryanwholey** [comment]
This would be a great feature addition! It is certainly a standard feature for a Terraform provider. I'll add this to the v0.1 milestones. I think this functionality should probably be in place before this project can be considered for 0.1 release. Thank you for the issue!

**Comment by ryanwholey** [comment]
Hi @cooperaj 

Support for importing the currently implemented resources  (cname/a records and groups) has been released in v0.0.9. Thank you again for submitting this issue! Cheers.
