### ISSUE TITLE
Address breaking changes for 2022.07.1

### ISSUE THREAD

**Issue by ryanwholey** [ryanwholey/terraform-provider-pihole#42]
Tests are failing with image tag >= 2022.07.1. Investigate, and fix. If any fixes require breaking changes to the provider, bump to the next major on release.

**Comment by jlilja** [comment]
This is addressed in https://github.com/ryanwholey/terraform-provider-pihole/pull/70, I believe.

**Comment by ryanwholey** [comment]
Tests are passing now thanks to @jlilja <3 closing
